# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  - group: Shoppinggroup

  # Agent VM image name
pool:
 name: 'shopping-agent'

stages:
- stage: Build_first_Dockerfile
  displayName: Build and push for frontend
  jobs:
  - job: BuildFrontend
    displayName: Build and push for frontend
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Build_second_Dockerfile
  displayName: Build and push backend
  jobs:
  - job: BuildBackend
    displayName: Build for 2nd Dockerfile
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository1)
        dockerfile: $(dockerfilePath1)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: creating_container
  displayName: creating container from images and deploy on aks cluster
  jobs:
  - job: containercreating
    displayName: container creating
    steps:
     - task: KubernetesManifest@1
       inputs:
         action: 'deploy'
         connectionType: 'azureResourceManager'
         azureSubscriptionConnection: 'Azure for Students(4f077f4d-a3e4-40bb-8c37-fb3e85c8e67d)'
         azureResourceGroup: 'social-media-group'
         kubernetesCluster: 'socialmedia_aks'
         namespace: 'shopping'
         manifests: |
           k8s/backend-deployment.yaml
           k8s/frontend-deployment.yaml
           k8s/mysql-deployment.yaml'