apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-backend
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-backend
  template:
    metadata:
      labels:
        app: shopping-backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:latest
        command: ['sh', '-c', 'until nc -z mysql 3306; do echo "waiting for mysql"; sleep 2; done;']
      containers:
      - name: backend
        image: shoopingreg.azurecr.io/shoopingbackend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mysql.shopping.svc.cluster.local"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "shoppingdb"

---
# ---------------------------
# Backend Service
# ---------------------------

apiVersion: v1
kind: Service
metadata:
  name: shopping-backend-svc
  namespace: shopping
spec:
  type: ClusterIP
  selector:
    app: shopping-backend
  ports:
  - protocol: TCP
    port: 3001        # ✅ Must match backend container port
    targetPort: 3001