apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-frontend
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-frontend
  template:
    metadata:
      labels:
        app: shopping-frontend
    spec:
      containers:
      - name: frontend
        image: shoopingreg.azurecr.io/shoopingfrontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://shopping-backend-svc.shopping.svc.cluster.local:3001"
          # ✅ Point frontend to backend service on correct port
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-frontend-svc
  namespace: shopping
spec:
  type: LoadBalancer
  selector:
    app: shopping-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
