apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-frontend
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-frontend
  template:
    metadata:
      labels:
        app: shopping-frontend
    spec:
      containers:
      - name: frontend
        image: shoopingreg.azurecr.io/shoopingfrontend:latest  # Replace with your CI/CD tag if needed
        ports:
        - containerPort: 3000   
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://shopping-backend-svc.shopping.svc.cluster.local:5000"
      
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-frontend-svc
  namespace: shopping
spec:
  type: LoadBalancer
  selector:
    app: shopping-frontend
  ports:
    - port: 80
      targetPort: 3000   
      protocol: TCP
