apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-frontend
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-frontend
  template:
    metadata:
      labels:
        app: shopping-frontend
    spec:
      containers:
      - name: frontend
        image: shoopingreg.azurecr.io/shoopingfrontend:$(tag)
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: shopping-frontend-svc
  namespace: shopping
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000  # or whatever port your container is exposing
      protocol: TCP
  selector:
    app: shopping-frontend  # must match pod labels