name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'azure-pipelines.yml'
      - 'k8s/**'

env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  FRONTEND_IMAGE: shoopingfrontend
  BACKEND_IMAGE: shoopingbackend
  TAG: ${{ github.run_number }}

jobs:
  build-frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ env.TAG }}

  build-backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ env.TAG }}

  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: shopping
          manifests: |
            k8s/backend-deployment.yaml
            k8s/frontend-deployment.yaml
            k8s/mysql-deployment.yaml
          images: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ env.TAG }}
